name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.HOST }}
        username: ubuntu-0925860
        password: ${{ secrets.PASSWORD }}
#         tryKeyboard: true
#         passphrase: ${{ secrets.PASSPHRASE }}
#         privateKey: ${{ secrets.PRIVATE_KEY}}
