name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        run: |
          cd test
          ls -a
        host: ${{ secrets.HOST }}
        username: ubuntu-0925860
        password: ${{ secrets.PASSWORD }}
#         tryKeyboard: true
#         passphrase: ${{ secrets.PASSPHRASE }}
#         privateKey: ${{ secrets.PRIVATE_KEY}}
